### ISSUE TITLE
spacebook as just a docs generation tool

### ISSUE THREAD

**Issue by rambabusaravanan** [broeker/spacebook#18]
**Is your feature request related to a problem? Please describe.**
Just a feature, not a problem.

**Describe the solution you'd like**
I am looking for a docs generation tool (a minimal version of yours) without any cms integration

**Describe alternatives you've considered**
gitbook-cli, docusarus are the options I tried for converting md into docs site.

**Additional context**
I just want to use eleventy to make it as simple as possible, but instead of writing css and layout for sidebar, thought of using a template. Would be good if you publish a minimal variant just for docs generation

**Comment by broeker** [comment]
Hi @rambabusaravanan thanks for the feedback. 

What you describe above is basically my goal. The CMS integration (along with search, dark mode, etc.) are all completely optional. The Netlify CMS in particular is disabled by default, and none of the Netlify scripts are loaded unless you enable that option. My goal is to keep this as minimal as possible but also provide some options for people not technical or who would otherwise prefer a CMS. 

Is there some reason that including the option is a problem for your goals?

**Comment by rambabusaravanan** [comment]
I like your approach and maybe using it in my next project where I expect the need for cms.

In the current case, I am using and deleting unwanted files and folders. For people looking like me, may fell in love if you have a another variant like 'spacebook-slim' or at least a cli like jhipster that generates the folder based on the needs.

This is just a feature request, feel free to close it

**Comment by broeker** [comment]
Yeah, I don't like that the default currently includes all of the files. I love the idea of cli or  at least just loading with a minimal amount of sample files. Thanks again for the feedback.

**Comment by broeker** [comment]
@rambabusaravanan just FYI this doesn't completely fulfill your request, but I've removed all of the docs/demo content from the main branch. Now when you install, you will get a single "hello world" page instead of all the docs. The CMS is disabled by default and you can simply ignore it, but it remains as an option.
